config/routes.rb
# -*- encoding : utf-8 -*-
RailsWebPrototype::Application.routes.draw do
  root :to => 'home#index'
  get "/home/index"
  devise_for :users
  devise_for :administrators
end

app/models/permission.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: permissions
#
#  id               :integer          not null, primary key
#  name             :string(255)
#  administrator_id :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Permission < ActiveRecord::Base
  validates :name,:presence => true, :allow_blank => false
  attr_accessible  :name,:permission_events_attributes 

  has_many :permission_events , :dependent => :destroy
  has_many :events  , :through => :permission_events

  has_many :administrator_permissions , :dependent => :destroy
  has_many :administrators  , :through => :administrator_permissions
  
  accepts_nested_attributes_for :permission_events , :allow_destroy => true
end

app/controllers/admin/permissions_controller.rb
# -*- encoding : utf-8 -*-
class Admin::PermissionsController < Admin::ResourceController

	def update
		@permission = Permission.find(params[:id])
		ActiveRecord::Base.transaction do
			@permission.permission_events.destroy_all();
			if @permission.update_attributes(params[:permission])
				redirect_to edit_admin_permission_path(@permission) ,:notice=>'成功'  and return
			else
				redirect_to edit_admin_permission_path(@permission),:error=>'失败'
			end
		end
	end

	def create
		create! do |success, failure|
	      failure.html { render :action=>:new,:error=>'失败' }
	      success.html { 
	      	redirect_to edit_admin_permission_path(resource),:notice=>'成功'
	      }
	    end
	end

	private

  def attributes
    %w(name)
  end
end

app/views/admin/permissions/_form.haml
= render "info_message"
= simple_form_for [ :admin, resource ], :html => { :class => 'form-horizontal' }  do |f|
  - attributes.each do |attr|
    = f.input attr
  - events = Event.all
  - event_ids = resource.event_ids
  - index = 0
  - Event.pluck("model_name").uniq.each do |model_name|
    .alert.alert-info= t("#{model_name}相关权限")
    %div
      - events.select{|e| e.model_name == model_name}.each do |e|
        = check_box_tag "permission[permission_events_attributes][#{index}][event_id]", e.id,event_ids.include?(e.id)
        = e.desc
        - index += 1
  = f.submit :class => 'btn btn-primary'
=link_to t("#{resource_class.name.underscore}.back_list") , collection_path

app/views/admin/permissions/index.html.haml
= content_for :backend_title,"管理 #{resource_class.model_name.human}"
= render "index", :attributes => attributes-%w(category)